# Generated by Django 5.1.6 on 2025-10-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("INSTRUCTOR", "Instructor"),
                    ("ALUMNO", "Alumno"),
                ],
                default="ALUMNO",
                max_length=20,
            ),
        ),
    ]
