# Generated by Django 5.1.6 on 2025-10-29 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationparticipant",
            name="last_read_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1, 1, 1, 0, 14, 44, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
